#PROMETHEUS
#PROMETHEUS_URL: "http://localhost:9090"
#START_TIME: datetime.datetime.strptime("2021-06-24 16:50:00", "%Y-%m-%d %H:%M:%S") # the cluster is 2h behind!
#END_TIME: datetime.datetime.strptime("2021-06-24 16:58:00", "%Y-%m-%d %H:%M:%S")
#METRIC_NAME: "request_duration_seconds_count"
#QUERY: 'rate(request_duration_seconds_count{job="kubernetes-service-endpoints", kubernetes_name="front-end", kubernetes_namespace="sock-shop", method="get", name="front-end", route="/", service="front-end", status_code="200"}[1m])'
#APP_URL: "http://localhost:5000/"
#UPDATE_DATA_ENDPOINT: "update_data"
#GET_RESULTS_ENDPOINT: "get_results"
#PLOT_RESULTS_ENDPOINT: "plot_results"
#UPDATE_INTERVAL_SEC: 10

#DUMMY
START_TIME: datetime.datetime.strptime("2014-04-01 14:00:00", "%Y-%m-%d %H:%M:%S")
END_TIME: datetime.datetime.strptime("2014-04-09 14:00:00", "%Y-%m-%d %H:%M:%S")
METRIC_NAME: "value"
APP_URL: "http://localhost:5000/"
UPDATE_DATA_ENDPOINT: "update_data"
GET_RESULTS_ENDPOINT: "get_results"
PLOT_RESULTS_ENDPOINT: "plot_results"
UPDATE_INTERVAL_SEC: 10
